// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function Bootstrap():Promise<model.BootstrapState>;

export function CompleteOnboarding(arg1:model.OnboardingRequest):Promise<model.BootstrapState>;

export function OpenWorkspace(arg1:model.OpenWorkspaceRequest):Promise<model.BootstrapState>;

export function RefreshProviders():Promise<model.BootstrapState>;
