// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function ApprovePairing(arg1:string):Promise<model.PairingSnapshot>;

export function Bootstrap():Promise<model.BootstrapState>;

export function CheckForUpdate():Promise<model.UpdateInfo>;

export function BridgeState():Promise<model.BridgeSnapshot>;

export function CompleteOnboarding(arg1:model.OnboardingRequest):Promise<model.BootstrapState>;

export function DeleteConversation(arg1:string):Promise<model.SessionSnapshot>;

export function DeleteWorkspaceConversation(arg1:model.WorkspaceCommandRequest):Promise<model.SessionSnapshot>;

export function GetSession(arg1:string):Promise<model.SessionSnapshot>;

export function GetWorkspaceSession(arg1:model.WorkspaceCommandRequest):Promise<model.SessionSnapshot>;

export function OpenWorkspace(arg1:model.OpenWorkspaceRequest):Promise<model.BootstrapState>;

export function PairingState():Promise<model.PairingSnapshot>;

export function RefreshProviders():Promise<model.BootstrapState>;

export function RejectPairing(arg1:string):Promise<model.PairingSnapshot>;

export function RemovePairedDevice(arg1:string):Promise<model.PairingSnapshot>;

export function RequestPairing(arg1:string):Promise<model.PairingSnapshot>;

export function ResolveApproval(arg1:model.ResolveApprovalRequest):Promise<model.SessionSnapshot>;

export function SendMessage(arg1:model.SendMessageRequest):Promise<model.SessionSnapshot>;
