// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function CompleteOnboarding(arg1) {
  return window['go']['main']['App']['CompleteOnboarding'](arg1);
}

export function OpenWorkspace(arg1) {
  return window['go']['main']['App']['OpenWorkspace'](arg1);
}

export function RefreshProviders() {
  return window['go']['main']['App']['RefreshProviders']();
}
