// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApprovePairing(arg1) {
  return window['go']['main']['App']['ApprovePairing'](arg1);
}

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function BridgeState() {
  return window['go']['main']['App']['BridgeState']();
}

export function CompleteOnboarding(arg1) {
  return window['go']['main']['App']['CompleteOnboarding'](arg1);
}

export function DeleteConversation(arg1) {
  return window['go']['main']['App']['DeleteConversation'](arg1);
}

export function DeleteWorkspaceConversation(arg1) {
  return window['go']['main']['App']['DeleteWorkspaceConversation'](arg1);
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function GetWorkspaceSession(arg1) {
  return window['go']['main']['App']['GetWorkspaceSession'](arg1);
}

export function OpenWorkspace(arg1) {
  return window['go']['main']['App']['OpenWorkspace'](arg1);
}

export function PairingState() {
  return window['go']['main']['App']['PairingState']();
}

export function RefreshProviders() {
  return window['go']['main']['App']['RefreshProviders']();
}

export function RejectPairing(arg1) {
  return window['go']['main']['App']['RejectPairing'](arg1);
}

export function RemovePairedDevice(arg1) {
  return window['go']['main']['App']['RemovePairedDevice'](arg1);
}

export function RequestPairing(arg1) {
  return window['go']['main']['App']['RequestPairing'](arg1);
}

export function ResolveApproval(arg1) {
  return window['go']['main']['App']['ResolveApproval'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}
